/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lengthConverter;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class lengthConverter extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public lengthConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        cbInput = new javax.swing.JComboBox<>();
        cbOutput = new javax.swing.JComboBox<>();
        tfInput = new javax.swing.JTextField();
        tfOutput = new javax.swing.JTextField();
        konversi = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Length Converter");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 153, 0));

        judul.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("Length Converter");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(145, 145, 145))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        cbInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometer", "Hektometer", "Dekameter", "Meter", "Desimeter", "Centimeter", "Milimeter", "Mile", "Feet", "Inch", " " }));
        getContentPane().add(cbInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 112, 92, 30));

        cbOutput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometer", "Hektometer", "Dekameter", "Meter", "Desimeter", "Centimeter", "Milimeter", "Mile", "Feet", "Inch", " " }));
        getContentPane().add(cbOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 233, 92, 30));

        tfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputActionPerformed(evt);
            }
        });
        getContentPane().add(tfInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 300, 30));

        tfOutput.setEditable(false);
        tfOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOutputActionPerformed(evt);
            }
        });
        getContentPane().add(tfOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 300, 30));

        konversi.setText("Konversi");
        konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiActionPerformed(evt);
            }
        });
        getContentPane().add(konversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 80, 30));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 80, 30));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 80, 30));

        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lengthConverter/background.png"))); // NOI18N
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputActionPerformed

    // method untuk exception (inputan harus angka)
    public void ConvertLength() throws AntiHuruf{
        double lengthDouble;
        String inputan = tfInput.getText();
        inputan = inputan.trim(); 
        
        try
        {
            lengthDouble = Double.parseDouble(inputan);
        }
        catch(NumberFormatException e)
        {
            throw new AntiHuruf();
        }
    }
    
    private void konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiActionPerformed
        // TODO add your handling code here:
       
        // memanggil try catch untuk menampilkan jOptionPane
        try {
            this.ConvertLength();
        } catch (AntiHuruf e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        // OPERASI PERHITUNGAN KONVERSI
        String box1 = (String)cbInput.getSelectedItem();
        String box2 = (String)cbOutput.getSelectedItem();
        
        // dari celcius
        if(box1.equals("Celcius") && box2.equals("Fahrenheit")){
            double c = Double.parseDouble(tfInput.getText());
            
            double k = (double)(c * 1.8 + 32);
            
            tfOutput.setText(String.valueOf(k));
        }
        
        if(box1.equals("Celcius") && box2.equals("Kelvin")){
            double c = Double.parseDouble(tfInput.getText());
            
            double f = (double)(c + 273);
            
            tfOutput.setText(String.valueOf(f));
        }
        
        if(box1.equals("Celcius") && box2.equals("Reamur")){
            double c = Double.parseDouble(tfInput.getText());
            
            double r = (double)(0.8 * c);
            
            tfOutput.setText(String.valueOf(r));
        }
       
        if(box1.equals("Celcius") && box2.equals("Celcius")){
            double c = Double.parseDouble(tfInput.getText());
            
            tfOutput.setText(String.valueOf(c));
        }
        
        // dari fahrenheit
        if(box1.equals("Fahrenheit") && box2.equals("Celcius")){
            double f = Double.parseDouble(tfInput.getText());
            
            double c = (double)((f - 32)* 0.56);
            
            tfOutput.setText(String.valueOf(c));
        }
        
        if(box1.equals("Fahrenheit") && box2.equals("Kelvin")){
            double f = Double.parseDouble(tfInput.getText());
            
            double k = (double)((f - 32)* 0.56 + 273);
            
            tfOutput.setText(String.valueOf(k));
        }
        
        if(box1.equals("Fahrenheit") && box2.equals("Reamur")){
            double f = Double.parseDouble(tfInput.getText());
            
            double r = (double)((f - 32) * (0.44));
            
            tfOutput.setText(String.valueOf(r));
        }
        
        if(box1.equals("Fahrenheit") && box2.equals("Fahrenheit")){
            double f = Double.parseDouble(tfInput.getText());
            
            tfOutput.setText(String.valueOf(f));
        }
        
        // dari kelvin 
        if(box1.equals("Kelvin") && box2.equals("Celcius")){
            double k = Double.parseDouble(tfInput.getText());
            
            double c = (double)(k - 273);
            
            tfOutput.setText(String.valueOf(c));
        }
        
        if(box1.equals("Kelvin") && box2.equals("Fahrenheit")){
            double k = Double.parseDouble(tfInput.getText());
            
            double f = (double)((k - 273) * 1.8 +32);
            
            tfOutput.setText(String.valueOf(f));
        }
        
        if(box1.equals("Kelvin") && box2.equals("Reamur")){
            double k = Double.parseDouble(tfInput.getText());
            
            double r = (double)((k - 273) * (0.8));
            
            tfOutput.setText(String.valueOf(r));
        }
        
        if(box1.equals("Kelvin") && box2.equals("Kelvin")){
            double k = Double.parseDouble(tfInput.getText());
            
            tfOutput.setText(String.valueOf(k));
        }

        // dari reamur 
        if(box1.equals("Reamur") && box2.equals("Celcius")){
            double r = Double.parseDouble(tfInput.getText());
            
            double c = (double)(r * (1.2));
            
            tfOutput.setText(String.valueOf(c));
        }
        
        if(box1.equals("Reamur") && box2.equals("Fahrenheit")){
            double r = Double.parseDouble(tfInput.getText());
            
            double f = (double)( (r * (1.8)) +32);
            
            tfOutput.setText(String.valueOf(f));
        }
        
        if(box1.equals("Reamur") && box2.equals("Kelvin")){
            double r = Double.parseDouble(tfInput.getText());
            
            double k = (double)((1.2 * r) + 273);
            
            tfOutput.setText(String.valueOf(k));
        }
        
        if(box1.equals("Reamur") && box2.equals("Reamur")){
            double r= Double.parseDouble(tfInput.getText());
            
            tfOutput.setText(String.valueOf(r));
        }
        
    }//GEN-LAST:event_konversiActionPerformed

    private void tfOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOutputActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        tfInput.setText("");
        tfOutput.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lengthConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lengthConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lengthConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lengthConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lengthConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbInput;
    private javax.swing.JComboBox<String> cbOutput;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel judul;
    private javax.swing.JButton keluar;
    private javax.swing.JButton konversi;
    private javax.swing.JLabel label2;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tfInput;
    private javax.swing.JTextField tfOutput;
    // End of variables declaration//GEN-END:variables
}
