/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lengthConverter;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class lengthConverter extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public lengthConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        cbInput = new javax.swing.JComboBox<>();
        cbOutput = new javax.swing.JComboBox<>();
        tfInput = new javax.swing.JTextField();
        tfOutput = new javax.swing.JTextField();
        konversi = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Length Converter");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 153, 0));

        judul.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("Length Converter");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(145, 145, 145))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        cbInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometer", "Hektometer", "Dekameter", "Meter", "Desimeter", "Centimeter", "Milimeter", "Mile", "Feet", "Inch" }));
        getContentPane().add(cbInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 112, 92, 30));

        cbOutput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometer", "Hektometer", "Dekameter", "Meter", "Desimeter", "Centimeter", "Milimeter", "Mile", "Feet", "Inch" }));
        getContentPane().add(cbOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 233, 92, 30));

        tfInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputActionPerformed(evt);
            }
        });
        getContentPane().add(tfInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 300, 30));

        tfOutput.setEditable(false);
        tfOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOutputActionPerformed(evt);
            }
        });
        getContentPane().add(tfOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 300, 30));

        konversi.setText("Konversi");
        konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiActionPerformed(evt);
            }
        });
        getContentPane().add(konversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 80, 30));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 80, 30));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 80, 30));

        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lengthConverter/background.png"))); // NOI18N
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputActionPerformed

    // method untuk exception (inputan harus angka)
    public void ConvertLength() throws AntiHuruf{
        double lengthDouble;
        String inputan = tfInput.getText();
        inputan = inputan.trim(); 
        
        try
        {
            lengthDouble = Double.parseDouble(inputan);
        }
        catch(NumberFormatException e)
        {
            throw new AntiHuruf();
        }
    }
    
    private void konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiActionPerformed
        // TODO add your handling code here:
       
        // memanggil try catch untuk menampilkan jOptionPane
        try {
            this.ConvertLength();
        } catch (AntiHuruf e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        // OPERASI PERHITUNGAN KONVERSI
        String box1 = (String)cbInput.getSelectedItem();
        String box2 = (String)cbOutput.getSelectedItem();
        
       //konversi 1 kilometer
        if(box1.equals("Kilometer") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }

        else if(box1.equals("Kilometer") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 10);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Kilometer") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 100);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Kilometer") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 1000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Kilometer") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 10000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Kilometer") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 100000 );

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Kilometer") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 1000000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Kilometer") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 0.6213711922);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Kilometer") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 3280.839895);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Kilometer") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 39370.07874);

            tfOutput.setText(String.valueOf(hasil));
        }

        //konversi 2 hektometer
        if(box1.equals("Hektometer") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.1);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 10);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 100);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 1000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 10000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 100000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.06213711922);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 328.0839895);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Hektometer") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 3937.007874);

            tfOutput.setText(String.valueOf(hasil));
        }
        //konversi 3 dekameter
        if(box1.equals("Dekameter") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.01);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.1);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 10);

            tfOutput.setText(String.valueOf(ambil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 100);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 1000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 10000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.006213711922);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 32.80839895);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Dekameter") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 393.7007874);

            tfOutput.setText(String.valueOf(hasil));
        }
        //konversi 4 meter
        if(box1.equals("Meter") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Meter") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.01);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Meter") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.1);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Meter") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }
        else if(box1.equals("Meter") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 10);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Meter") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 100);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Meter") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 1000);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Meter") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0006213711922);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Meter") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 3.280839895);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Meter") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 39.37007874);

            tfOutput.setText(String.valueOf(hasil));
        }
        //konversi 5 desimeter
        if(box1.equals("Desimeter") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.01);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.1);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 10);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 100);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0000621371);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.3280839895);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Desimeter") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 3.937007874);

            tfOutput.setText(String.valueOf(hasil));
        }
        //konversi 6 centimeter
        if(box1.equals("Centimeter") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.00001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.01);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.1);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 10);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0000062137);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.032808399);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Centimeter") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.3937007874);

            tfOutput.setText(String.valueOf(hasil));
        }
        //konversi 7 milimeter
        if(box1.equals("Milimeter") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.000001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.00001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.001);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.01);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 0.1);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 6.213711922);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0032808399);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Milimeter") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0393700787);

            tfOutput.setText(String.valueOf(hasil));
        }
        //konversi 8 mile
        if(box1.equals("Mile") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 1.609344 );

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Mile") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 16.09344);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Mile") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 160.9344);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Mile") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 1609.344);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Mile") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 16093.44);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Mile") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 160934.4 );

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Mile") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 1609344);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Mile") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }

        else if(box1.equals("Mile") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 5280);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Mile") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 63360);

            tfOutput.setText(String.valueOf(hasil));
        }

        //konversi 10 feet
        if(box1.equals("Feet") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0003048);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Feet") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.003048);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Feet") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.03048);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Feet") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.3048);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Feet") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 3.048);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Feet") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 30.48);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Feet") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 304.8);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Feet") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 0.0001893939);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Feet") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }
        else if(box1.equals("Feet") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 12);

            tfOutput.setText(String.valueOf(hasil));
        }
        //konversi 11 inch
        if(box1.equals("Inch") && box2.equals("Kilometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0000254);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Hektometer"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.000254);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Dekameter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.00254);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Meter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.0254);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Desimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 0.254);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Centimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double)(ambil * 2.54);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Milimeter"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 25.4);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Mile"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 0.0000157828);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Feet"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            double hasil = (double) (ambil * 0.0833333333);

            tfOutput.setText(String.valueOf(hasil));
        }
        else if(box1.equals("Inch") && box2.equals("Inch"))
        {
            double ambil = Double.parseDouble(tfInput.getText());

            tfOutput.setText(String.valueOf(ambil));
        }
    }//GEN-LAST:event_konversiActionPerformed

    private void tfOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOutputActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        tfInput.setText("");
        tfOutput.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lengthConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lengthConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lengthConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lengthConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lengthConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbInput;
    private javax.swing.JComboBox<String> cbOutput;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel judul;
    private javax.swing.JButton keluar;
    private javax.swing.JButton konversi;
    private javax.swing.JLabel label2;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tfInput;
    private javax.swing.JTextField tfOutput;
    // End of variables declaration//GEN-END:variables
}
